### ISSUE TITLE
Unable to use on nodejs due to window not being available

### ISSUE THREAD

**Issue by xPaw** [ritz078/embed.js#244] opened 2017-04-27 19:04 UTC
Like here: https://github.com/ritz078/embed.js/blob/37a302acbee12f035f9b8a90b33a6456c9f0be61/src/js/main.js#L88-L95

Also `XMLHttpRequest` is not available (comes from `unfetch`)

**Comment by ritz078** [comment] 2017-05-15 12:20
Duplicate of #180

**Closed by ritz078** 2017-05-15 12:20 UTC
